### ISSUE TITLE
feature request - ListView

### ISSUE THREAD

**Issue by Shmoopy02** [AngryCarrot789/CoolDarkThemeThingy#1]
Hey, found this on Reddit. Really nice job. Showed a few devs at work and they want dark theme option on all our internal tools.

Quick feature request … could you theme ListView? We use them extensively for displaying logs in app.

**Comment by AngryCarrot789** [comment]
yeah i can do that. will (hopefully) be done in maybe 10 mins

**Comment by Shmoopy02** [comment]
Wow awesome thank you!
