### ISSUE TITLE
minor issue - dark text in searchable ComboBox

### ISSUE THREAD

**Issue by Shmoopy02** [AngryCarrot789/CoolDarkThemeThingy#2]
Heya. Loving this theme. Found a minor issue when you make a ComboBox searchable. The search text while typing is super dark. 

Here's the XAML for the ComboBox. Just populate it with a few dozen items and try to search:

`<ComboBox Name="cBox_Test_1" IsTextSearchEnabled="True" IsTextSearchCaseSensitive="False" IsEditable="True"></ComboBox>`

Here's an image of the dark text. Let me know if any questions:

https://imgur.com/CgajAwd

**Comment by AngryCarrot789** [comment]
Fixed :) didnt change the default foreground, now set to ControlDefaultForeground (which is white-ish). Also fixed the caret brush (the little line thing) from black to white.

**Comment by Shmoopy02** [comment]
Looks good. Thanks!
