### ISSUE TITLE
Active Tab Visibility

### ISSUE THREAD

**Issue by Shmoopy02** [AngryCarrot789/CoolDarkThemeThingy#3]
Hey, giving this thing a real workout with multiple users at work. The only complaint left is the visibility of the active tab in a TabControl. It doesn't have any contrast. Pic for reference:

https://imgur.com/a/RibLc1a

**Comment by Shmoopy02** [comment]
Also, this code is so useful I'd like to donate you a few bucks. Is there a good way to do that?

**Comment by AngryCarrot789** [comment]
> Also, this code is so useful I'd like to donate you a few bucks. Is there a good way to do that?
oh.. thanks :> im not actually legally allowed to have paypal in the uk yet... rip. although i guess one way could be through steam (id/url thing is backtothepresent1969).
glad you like the theme too, and i'll fix that tab item visibility thing too

**Comment by Shmoopy02** [comment]
> backtothepresent1969

Works perfectly thank you. Will contact you on Steam. ;)
