### ISSUE TITLE
Searchable combo box dark text while editing

### ISSUE THREAD

**Issue by Shmoopy02** [AngryCarrot789/CoolDarkThemeThingy#4]
Hey, think I found one last issue hehe. We have a lot of searchable Combo Boxes and the text when you are inputting is really dark. Pics here:

https://imgur.com/a/T0ygwmA
https://imgur.com/a/Z2fX4xg

Using standard combo boxes with following enabled ...

<ComboBox IsTextSearchEnabled="True" IsEditable="True"/>

… and the ComboBox.ItemsSource is bound to a List<string>.

**Comment by Shmoopy02** [comment]
Wait hmmm this sounded familiar. Looks like you closed out an issue for the same thing earlier. Did it get undone somehow? =(

https://github.com/AngryCarrot789/CoolDarkThemeThingy/issues/2

**Comment by Shmoopy02** [comment]
Also just to make sure I re-downloaded the zipped source again just now. Pretty sure I have the latest.

**Comment by AngryCarrot789** [comment]
I think I already fixed this before. if it broke again, I'll try and fix it
(might have left out a few lines of code) in a few hours or so (out atm)

**Comment by AngryCarrot789** [comment]
long delay soz, but i think i fixed it
somehow the code from when i set the Foreground in the editable style had just vanished... strange.
but it seems to work now.

**Comment by Shmoopy02** [comment]
Looks good!
